// <auto-generated />
using System;
using BeFit.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeFit.Persistence.Migrations
{
    [DbContext(typeof(BeFitDbContext))]
    [Migration("20241010174747_basketoperations")]
    partial class basketoperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeFit.Domain.Entities.Abstract.Nutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertiesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Nutrients", (string)null);

                    b.HasDiscriminator().HasValue("Nutrient");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NutrientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NutrientId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Dislike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dislikes", (string)null);

                    b.HasDiscriminator().HasValue("Dislike");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Exercise.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActivityCoefficient")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Exercise.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WOBurnedCalorie")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasDiscriminator().HasValue("Exercise");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BeFit.Domain.Entities.FoodBasket.BasketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Measure")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NutrientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("NutrientId");

                    b.ToTable("BasketItems");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.FoodBasket.FoodBasket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NutrientPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalCalorie")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCarb")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCholesterol")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalFat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalMagnesium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalProtein")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSalt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSodium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSugar")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NutrientPropertiesId");

                    b.ToTable("FoodBaskets");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Images", (string)null);

                    b.HasDiscriminator().HasValue("Image");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Likes", (string)null);

                    b.HasDiscriminator().HasValue("Like");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Macros.Carbohydrate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NutrientPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SugarWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NutrientPropertiesId");

                    b.ToTable("Carbohydrate");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Macros.Fat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CholesterolWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NutrientPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NutrientPropertiesId");

                    b.ToTable("Fat");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Macros.Protein", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NutrientPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NutrientPropertiesId");

                    b.ToTable("Protein");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Minerals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Calcium")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Iron")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Magnesium")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NutrientPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Phosphorus")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Potassium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Sodium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Sulfur")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NutrientPropertiesId");

                    b.ToTable("Minerals");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.NutrientProperties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Calories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Carbohydrate100gr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CholesterolWeight100gr")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fat100gr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Magnesium100gr")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NutrientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Protein100gr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Salt100gr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Sodium100gr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SugarWeight100gr")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NutrientId")
                        .IsUnique();

                    b.ToTable("NutrientProperties");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Salt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NutrientPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NutrientPropertiesId");

                    b.ToTable("Salt");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.UserProperties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BodyDecision")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyCalories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FatBurnCalories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FatRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaintenanceCalories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NeededCarbohydrate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NeededFat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NeededProtein")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SuggestedFatRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SuggestedWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightGainCalories")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProperties");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Vitamins", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("B1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("B12")
                        .HasColumnType("numeric");

                    b.Property<decimal>("B2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("B3")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("E")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FolicAcid")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NutrientPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NutrientPropertiesId");

                    b.ToTable("Vitamins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Drink", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Abstract.Nutrient");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("Drink");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Food", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Abstract.Nutrient");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasIndex("CategoryId");

                    b.ToTable("Nutrients", t =>
                        {
                            t.Property("CategoryId")
                                .HasColumnName("Food_CategoryId");
                        });

                    b.HasDiscriminator().HasValue("Food");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.CommentDislike", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Dislike");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("CommentDislike");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.PostDislike", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Dislike");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("PostDislike");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Cardio", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Exercise.Exercise");

                    b.Property<decimal>("Minutes")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Cardio");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Training", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Exercise.Exercise");

                    b.Property<decimal>("BurnedCaloriePer12Reps")
                        .HasColumnType("numeric");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasIndex("UserId");

                    b.ToTable("Exercises", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("Training_UserId");
                        });

                    b.HasDiscriminator().HasValue("Training");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.CategoryImage", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Image");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("CategoryImage");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.NutrientImage", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Image");

                    b.Property<Guid>("NutrientId")
                        .HasColumnType("uuid");

                    b.HasIndex("NutrientId");

                    b.HasDiscriminator().HasValue("FoodImage");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.PostImage", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Image");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasIndex("PostId");

                    b.HasDiscriminator().HasValue("PostImage");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.CommentLike", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Like");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("CommentLike");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.PostLike", b =>
                {
                    b.HasBaseType("BeFit.Domain.Entities.Like");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("PostLike");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Category", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Abstract.Nutrient", null)
                        .WithMany("Categories")
                        .HasForeignKey("NutrientId");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Comment", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Domain.Entities.Identity.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.FoodBasket.BasketItem", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.FoodBasket.FoodBasket", "Basket")
                        .WithMany("Nutrients")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Domain.Entities.Abstract.Nutrient", "Nutrient")
                        .WithMany()
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.FoodBasket.FoodBasket", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.NutrientProperties", null)
                        .WithMany("Baskets")
                        .HasForeignKey("NutrientPropertiesId");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Domain.Entities.Identity.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Macros.Carbohydrate", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.NutrientProperties", "NutrientProperties")
                        .WithMany()
                        .HasForeignKey("NutrientPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientProperties");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Macros.Fat", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.NutrientProperties", "NutrientProperties")
                        .WithMany()
                        .HasForeignKey("NutrientPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientProperties");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Macros.Protein", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.NutrientProperties", "NutrientProperties")
                        .WithMany()
                        .HasForeignKey("NutrientPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientProperties");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Minerals", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.NutrientProperties", "NutrientProperties")
                        .WithMany()
                        .HasForeignKey("NutrientPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientProperties");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.NutrientProperties", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Abstract.Nutrient", "Nutrient")
                        .WithOne("Properties")
                        .HasForeignKey("BeFit.Domain.Entities.NutrientProperties", "NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Post", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Salt", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.NutrientProperties", "NutrientProperties")
                        .WithMany()
                        .HasForeignKey("NutrientPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientProperties");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.UserProperties", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Exercise.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("BeFit.Domain.Entities.Identity.User", "User")
                        .WithOne("Properties")
                        .HasForeignKey("BeFit.Domain.Entities.UserProperties", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Vitamins", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.NutrientProperties", "NutrientProperties")
                        .WithMany()
                        .HasForeignKey("NutrientPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientProperties");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Drink", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Category", null)
                        .WithMany("Drinks")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Food", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Category", null)
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.CommentDislike", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Comment", "Comment")
                        .WithMany("Dislikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Domain.Entities.Identity.User", "User")
                        .WithMany("CommentDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.PostDislike", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Post", "Post")
                        .WithMany("Dislikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Domain.Entities.Identity.User", "User")
                        .WithMany("PostDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Cardio", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.User", null)
                        .WithMany("Cardios")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Training", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Identity.User", null)
                        .WithMany("Trainings")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.CategoryImage", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Category", "Category")
                        .WithMany("Images")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.NutrientImage", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Abstract.Nutrient", "Nutrient")
                        .WithMany("Images")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.PostImage", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.CommentLike", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Domain.Entities.Identity.User", "User")
                        .WithMany("CommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.PostLike", b =>
                {
                    b.HasOne("BeFit.Domain.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit.Domain.Entities.Identity.User", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Abstract.Nutrient", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Images");

                    b.Navigation("Properties")
                        .IsRequired();
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Category", b =>
                {
                    b.Navigation("Drinks");

                    b.Navigation("Foods");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Dislikes");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.FoodBasket.FoodBasket", b =>
                {
                    b.Navigation("Nutrients");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("Cardios");

                    b.Navigation("CommentDislikes");

                    b.Navigation("CommentLikes");

                    b.Navigation("Comments");

                    b.Navigation("PostDislikes");

                    b.Navigation("PostLikes");

                    b.Navigation("Posts");

                    b.Navigation("Properties")
                        .IsRequired();

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.NutrientProperties", b =>
                {
                    b.Navigation("Baskets");
                });

            modelBuilder.Entity("BeFit.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Dislikes");

                    b.Navigation("Images");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
