name: .NET CI Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore


      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet-ef to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
        
      - name: Apply database migrations
        run: dotnet ef database update --no-build --project "BeFit.Persistence.csproj"
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
